// <auto-generated />
namespace WebsiteBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update1212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1212));
        
        string IMigrationMetadata.Id
        {
            get { return "202312110519574_Update1212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
