// <auto-generated />
namespace WebsiteBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update15123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update15123));
        
        string IMigrationMetadata.Id
        {
            get { return "202312150627116_update15123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
